import { ChangeEvent, useEffect, useState } from "react";
import type { ApiRequest } from "./SalesWorkspace";

type ImportRow = { id:string; rowNumber:number; name:string; category:string|null; countUnit:string; parLevel:string|null; validationErrors:string[]; selected:boolean|null; createdInventoryItemId:string|null };
type InventoryImport = { id:string; originalFilename:string; contentHash:string; status:string; revision:number; rows:ImportRow[] };

export function InventoryImportPanel({request,onApplied}:{request:ApiRequest;onApplied:(value:InventoryImport)=>Promise<void>}) {
  const [value,setValue]=useState<InventoryImport|null>(null);
  const [showAll,setShowAll]=useState(false);
  const [busy,setBusy]=useState(false), [error,setError]=useState(""), [notice,setNotice]=useState("");
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;setError("");setNotice("");if(file.size>1024*1024){setError("Choose a CSV file no larger than 1 MiB.");return}setBusy(true);try{const form=new FormData();form.append("file",file);const next=await request<InventoryImport>("/v1/inventory-imports",{method:"POST",body:form});let valid=0;next.rows=next.rows.map(row=>({...row,selected:row.validationErrors.length===0&&valid++<20}));setValue(next);setShowAll(next.rows.length<=20);setNotice(`Ready to review: ${next.rows.length} ${next.rows.length===1?"item":"items"}. Nothing has been added yet.`)}catch(reason){setError(reason instanceof Error?reason.message:"We couldn't read this inventory file. Try exporting it again.")}finally{setBusy(false)}}
  function update(id:string,patch:Partial<ImportRow>){setValue(current=>current?{...current,rows:current.rows.map(row=>{if(row.id!==id)return row;const next={...row,...patch};return {...next,validationErrors:validateInventoryRow(next)}})}:current)}
  async function apply(){if(!value)return;setBusy(true);setError("");setNotice("");let applied=false;try{const next=await request<InventoryImport>(`/v1/inventory-imports/${value.id}`,{method:"PUT",body:JSON.stringify({revision:value.revision,rows:value.rows.map(({id,selected,name,category,countUnit,parLevel})=>({id,selected:Boolean(selected),name,category:category?.trim()||null,countUnit,parLevel:parLevel?.trim()||null}))})});applied=true;setValue(next);setNotice("Inventory items imported.");await onApplied()}catch(reason){setError(applied?`Inventory items were imported, but the next step could not open. ${reason instanceof Error?reason.message:"Try opening Inventory again."}`:reason instanceof Error?reason.message:"The import couldn't be applied. Review the selected rows and try again.")}finally{setBusy(false)}}
  const selectedValid=value?.rows.filter(row=>row.selected&&row.validationErrors.length===0).length??0;
  const visibleRows=value?.rows.filter(row=>showAll||Boolean(row.selected)||row.validationErrors.length>0)??[], hiddenRows=(value?.rows.length??0)-visibleRows.length;
  return <section className="inventory-import-panel" aria-labelledby="inventory-import-heading"><div className="list-heading"><div><p className="section-code">Flexible CSV import</p><h2 id="inventory-import-heading">Upload any inventory CSV</h2></div></div><p>Use your existing inventory export — columns and headings do not need to match a template. We’ll read the items for you to review. Nothing is added until you apply them.</p><label className="file-button import-file">{busy?"Reading inventory…":"Choose CSV"}<input type="file" accept=".csv,text/csv" disabled={busy} onChange={upload}/></label><small>Any CSV layout · maximum file size 1 MiB.</small>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="success-notice" role="status">{notice}</p>}{value&&value.status!=="applied"&&<div className="import-preview"><h3>Review {value.originalFilename}</h3><p>{selectedValid} valid items selected. Start with these items for the first count; duplicates and unclear values stay excluded.</p>{visibleRows.map(row=><article className="import-row" key={row.id}><label className="active-toggle"><input type="checkbox" checked={Boolean(row.selected)} disabled={row.validationErrors.length>0} onChange={e=>update(row.id,{selected:e.target.checked})}/> Include item {row.rowNumber-1}</label>{row.validationErrors.length>0&&<p className="form-error">{row.validationErrors.join(" ")} Correct the extracted values below to include this item.</p>}<div className="inventory-form-fields"><label>Name<input value={row.name} maxLength={50} onChange={e=>update(row.id,{name:e.target.value})}/></label><label>Category <span>Optional</span><input value={row.category??""} maxLength={20} onChange={e=>update(row.id,{category:e.target.value})}/></label><label>Count unit<input value={row.countUnit} maxLength={40} onChange={e=>update(row.id,{countUnit:e.target.value})}/></label><label>Par level <span>Optional</span><input inputMode="decimal" value={row.parLevel??""} onChange={e=>update(row.id,{parLevel:e.target.value})}/></label></div></article>)}{hiddenRows>0&&<button className="text-button import-show-all" type="button" onClick={()=>setShowAll(true)}>Review {hiddenRows} more {hiddenRows===1?"item":"items"}</button>}<button className="ledger-button" type="button" disabled={busy||selectedValid===0} onClick={()=>void apply()}>{busy?"Applying…":`Apply ${selectedValid} items`}</button></div>}</section>
}

function validateInventoryRow(row:ImportRow):string[]{const errors:string[]=[];if(!row.name.trim()||row.name.trim().length>50)errors.push("Name must be between 1 and 50 characters.");if((row.category?.trim().length??0)>20)errors.push("Category must be 20 characters or fewer.");if(!row.countUnit.trim()||row.countUnit.trim().length>20)errors.push("Count unit must be between 1 and 20 characters.");if(row.parLevel?.trim()&&!/^\d+(?:\.\d{1,6})?$/.test(row.parLevel.trim()))errors.push("Par level must be a nonnegative number with up to 6 decimal places.");return errors}
