import { ChangeEvent, useState } from "react";
import type { ApiRequest } from "./SalesWorkspace";

type ImportRow = { id:string; rowNumber:number; name:string; category:string|null; countUnit:string; parLevel:string|null; validationErrors:string[]; selected:boolean|null; createdInventoryItemId:string|null };
type InventoryImport = { id:string; originalFilename:string; contentHash:string; status:string; revision:number; rows:ImportRow[] };

export function InventoryImportPanel({request,onApplied}:{request:ApiRequest;onApplied:()=>Promise<void>}) {
  const [value,setValue]=useState<InventoryImport|null>(null);
  const [showAll,setShowAll]=useState(false);
  const [busy,setBusy]=useState(false), [error,setError]=useState(""), [notice,setNotice]=useState("");
  function downloadTemplate(){const blob=new Blob(["name,count_unit,category,par_level\nChicken breast,lb,Protein,25\n"],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="parline-inventory-template.csv";a.click();URL.revokeObjectURL(a.href)}
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;setError("");setNotice("");if(file.size>1024*1024){setError("Choose a CSV file no larger than 1 MiB.");return}setBusy(true);try{const form=new FormData();form.append("file",file);const next=await request<InventoryImport>("/v1/inventory-imports",{method:"POST",body:form});let valid=0;next.rows=next.rows.map(row=>({...row,selected:row.validationErrors.length===0&&valid++<20}));setValue(next);setShowAll(next.rows.length<=20);setNotice(`Preview ready: ${next.rows.length} ${next.rows.length===1?"row":"rows"}. Review before applying.`)}catch(reason){setError(reason instanceof Error?reason.message:"The CSV couldn't be previewed. Check the template and try again.")}finally{setBusy(false)}}
  function update(id:string,patch:Partial<ImportRow>){setValue(current=>current?{...current,rows:current.rows.map(row=>row.id===id?{...row,...patch}:row)}:current)}
  async function apply(){if(!value)return;setBusy(true);setError("");setNotice("");let applied=false;try{const next=await request<InventoryImport>(`/v1/inventory-imports/${value.id}`,{method:"PUT",body:JSON.stringify({revision:value.revision,rows:value.rows.map(({id,selected,name,category,countUnit,parLevel})=>({id,selected:Boolean(selected),name,category:category?.trim()||null,countUnit,parLevel:parLevel?.trim()||null}))})});applied=true;setValue(next);setNotice("Inventory items imported.");await onApplied()}catch(reason){setError(applied?`Inventory items were imported, but the next step could not open. ${reason instanceof Error?reason.message:"Try opening Inventory again."}`:reason instanceof Error?reason.message:"The import couldn't be applied. Review the selected rows and try again.")}finally{setBusy(false)}}
  const selectedValid=value?.rows.filter(row=>row.selected&&row.validationErrors.length===0).length??0;
  const visibleRows=value?.rows.filter(row=>showAll||Boolean(row.selected)||row.validationErrors.length>0)??[], hiddenRows=(value?.rows.length??0)-visibleRows.length;
  return <section className="inventory-import-panel" aria-labelledby="inventory-import-heading"><div className="list-heading"><div><p className="section-code">Bring your records</p><h2 id="inventory-import-heading">Import inventory CSV</h2></div><button className="text-button" type="button" onClick={downloadTemplate}>Download template</button></div><p>Upload an existing inventory spreadsheet to preview it. Nothing is added until you apply it.</p><label className="file-button import-file">{busy?"Working…":"Choose CSV"}<input type="file" accept=".csv,text/csv" disabled={busy} onChange={upload}/></label><small>Maximum file size: 1 MiB.</small>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="success-notice" role="status">{notice}</p>}{value&&value.status!=="applied"&&<div className="import-preview"><h3>Review {value.originalFilename}</h3><p>{selectedValid} valid rows selected. Start with these items for the first count; duplicates and invalid rows stay excluded.</p>{visibleRows.map(row=><article className="import-row" key={row.id}><label className="active-toggle"><input type="checkbox" checked={Boolean(row.selected)} disabled={row.validationErrors.length>0} onChange={e=>update(row.id,{selected:e.target.checked})}/> Include row {row.rowNumber}</label>{row.validationErrors.length>0&&<p className="form-error">{row.validationErrors.join(" ")} Fix the CSV and upload it again; invalid rows stay excluded.</p>}<div className="inventory-form-fields"><label>Name<input value={row.name} maxLength={50} onChange={e=>update(row.id,{name:e.target.value})}/></label><label>Category <span>Optional</span><input value={row.category??""} maxLength={20} onChange={e=>update(row.id,{category:e.target.value})}/></label><label>Count unit<input value={row.countUnit} maxLength={40} onChange={e=>update(row.id,{countUnit:e.target.value})}/></label><label>Par level <span>Optional</span><input inputMode="decimal" value={row.parLevel??""} onChange={e=>update(row.id,{parLevel:e.target.value})}/></label></div></article>)}{hiddenRows>0&&<button className="text-button import-show-all" type="button" onClick={()=>setShowAll(true)}>Review {hiddenRows} more {hiddenRows===1?"row":"rows"}</button>}<button className="ledger-button" type="button" disabled={busy||selectedValid===0} onClick={()=>void apply()}>{busy?"Applying…":`Apply ${selectedValid} items`}</button></div>}</section>
}
